server:
  port: 8083
spring:
  application:
    name: feign
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,bus-refresh

ttsales:
  points:
    pointsWxToken:
       tokenCookieName: POINTS_WX_TOKEN
       openIdHeaderName: X-OPENID
       openIdAttributeName: X-OPENID
       tokenCookieTtl: 1800000
