spring:
        cloud:
                config:
                        name: wechat
                        lable: master
                        discovery:
                                enabled: true
                                serviceId: wechat

eureka:
        client:
                serviceUrl:
                        defaultZone: http://localhost:8888/eureka/
